### ISSUE TITLE
Error on output

### ISSUE THREAD

**Issue by marcobelmonte** [p33kab00/shellshock-scan#1]
FYI:

![image](https://user-images.githubusercontent.com/4238826/42438168-14a7de7a-8314-11e8-94df-5873181d15bf.png)

**Comment by p33kab00** [comment]
Dah! GIve it a go again.

**Comment by marcobelmonte** [comment]
That fixed it :-) Thanks for the quick support and thanks for sharing your code
 👍

**Comment by p33kab00** [comment]
Thanks for keeping me on the toes ;-)
